(define (problem example-auv)
  (:domain suave)

  (:objects
    pipeline - pipeline
    bluerov - robot
    qa_search_efficiency_low 0.25_decimal qa_water_visibility_high 3.25_decimal qa_water_visibility_low 1.25_decimal <_string qa_search_efficiency_medium 0.5_decimal qa_motion_efficiency_degraded 0.75_decimal battery_level qa_inspect_efficiency_high 1.0_decimal qa_search_efficiency_high qa_motion_efficiency_normal qa_water_visibility_medium 2.25_decimal fd_spiral_high fd_follow_pipeline fd_spiral_medium fd_all_thrusters c_thruster_2 performance c_thruster_4 fd_spiral_low fd_recover_thrusters obs_water_visibility c_thruster_1 c_thruster_3 c_thruster_5 c_thruster_6 safety energy - object
)

  (:init
    (c_status c_thruster_4 false_string)

    (action_requires a_search_pipeline f_generate_search_path f_maintain_motion)
    (action_requires a_inspect_pipeline f_follow_pipeline f_maintain_motion)
    (system_in_mode f_maintain_motion fd_unground)
    (system_in_mode f_follow_pipeline fd_unground)
    (system_in_mode f_generate_search_path fd_unground)

    (hasValue qa_search_efficiency_low 0.25_decimal)
    (hasValue qa_water_visibility_high 3.25_decimal)
    (hasValue qa_water_visibility_low 1.25_decimal)
    (qa_comparison_operator water_visibility <_string)
    (hasValue qa_search_efficiency_medium 0.5_decimal)
    (hasValue qa_motion_efficiency_degraded 0.75_decimal)
    (qa_comparison_operator battery_level <_string)
    (hasValue qa_inspect_efficiency_high 1.0_decimal)
    (hasValue qa_search_efficiency_high 1.0_decimal)
    (hasValue qa_motion_efficiency_normal 1.0_decimal)
    (hasValue qa_water_visibility_medium 2.25_decimal)
    (solvesF fd_spiral_high f_generate_search_path)
    (hasQAestimation fd_follow_pipeline qa_inspect_efficiency_high)
    (isQAtype qa_water_visibility_medium water_visibility)
    (solvesF fd_spiral_medium f_generate_search_path)
    (requiresC fd_all_thrusters c_thruster_2)
    (isQAtype qa_search_efficiency_low performance)
    (requiresC fd_all_thrusters c_thruster_4)
    (hasQAestimation fd_spiral_high qa_search_efficiency_high)
    (isQAtype qa_water_visibility_high water_visibility)
    (hasQAestimation fd_spiral_low qa_search_efficiency_low)
    (isQAtype qa_motion_efficiency_degraded performance)
    (hasQAestimation fd_spiral_medium qa_water_visibility_medium)
    (hasQAestimation fd_spiral_medium qa_search_efficiency_medium)
    (isQAtype qa_water_visibility_low water_visibility)
    (solvesF fd_recover_thrusters f_maintain_motion)
    (isQAtype obs_water_visibility water_visibility)
    (requiresC fd_all_thrusters c_thruster_1)
    (solvesF fd_follow_pipeline f_follow_pipeline)
    (isQAtype qa_inspect_efficiency_high performance)
    (solvesF fd_all_thrusters f_maintain_motion)
    (isQAtype qa_search_efficiency_medium performance)
    (isQAtype qa_search_efficiency_high performance)
    (hasQAestimation fd_spiral_high qa_water_visibility_high)
    (solvesF fd_spiral_low f_generate_search_path)
    (hasQAestimation fd_spiral_low qa_water_visibility_low)
    (isQAtype qa_motion_efficiency_normal performance)
    (hasQAestimation fd_recover_thrusters qa_motion_efficiency_degraded)
    (requiresC fd_all_thrusters c_thruster_3)
    (hasQAestimation fd_all_thrusters qa_motion_efficiency_normal)
    (requiresC fd_all_thrusters c_thruster_5)
    (requiresC fd_all_thrusters c_thruster_6)
    (QAvalue qa_water_visibility_high)
    (FunctionDesign fd_follow_pipeline)
    (QAvalue obs_water_visibility)
    (QAvalue qa_search_efficiency_medium)
    (Component c_thruster_6)
    (FunctionDesign fd_all_thrusters)
    (QAvalue qa_water_visibility_low)
    (Component c_thruster_4)
    (QualityAttributeType water_visibility)
    (QAvalue qa_inspect_efficiency_high)
    (QualityAttributeType battery_level)
    (FunctionDesign fd_spiral_low)
    (Component c_thruster_3)
    (QAvalue qa_motion_efficiency_degraded)
    (QAvalue qa_water_visibility_medium)
    (QAvalue qa_search_efficiency_high)
    (Function f_maintain_motion)
    (Function f_follow_pipeline)
    (FunctionDesign fd_recover_thrusters)
    (Function f_generate_search_path)
    (FunctionDesign fd_spiral_medium)
    (Component c_thruster_2)
    (FunctionDesign fd_spiral_high)
    (QualityAttributeType safety)
    (QualityAttributeType energy)
    (QAvalue qa_motion_efficiency_normal)
    (Component c_thruster_5)
    (QAvalue qa_search_efficiency_low)
    (QualityAttributeType performance)
    (Component c_thruster_1)
    (FunctionDesign fd_unground)
  )

  (:goal (and
    (robot_started bluerov)
    (pipeline_found pipeline)
    (pipeline_inspected pipeline)
  ))
)
