// Copyright 2019 Intelligent Robotics Lab
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef PLANSYS2_POPF_PLAN_SOLVER__POPF_PLAN_SOLVER_HPP_
#define PLANSYS2_POPF_PLAN_SOLVER__POPF_PLAN_SOLVER_HPP_

#include <filesystem>
#include <optional>
#include <memory>
#include <string>

#include "plansys2_core/PlanSolverBase.hpp"

// using namespace std::chrono_literals;
using std::chrono_literals::operator""s;

namespace plansys2
{

/**
 * @class plansys2::POPFPlanSolver
 * @brief Plan solver implementation that uses the POPF planning system.
 *
 * This class implements the PlanSolverBase interface using the POPF (Partial Order Planning Forward)
 * planner. It handles writing domain and problem files to disk, executing the planner,
 * and parsing the resulting plan.
 */
class POPFPlanSolver : public PlanSolverBase
{
private:
  std::string arguments_parameter_name_;
  std::string output_dir_parameter_name_;
  bool cancel_requested_;

public:
  /**
   * @brief Default constructor.
   */
  POPFPlanSolver();

  /**
   * @brief Creates folder structure for storing temporary planning files.
   *
   * @param[in] node_namespace Namespace to use for folder structure.
   * @return std::optional<std::filesystem::path> Created folder path if successful,
   *        std::nullopt on failure.
   */
  std::optional<std::filesystem::path> create_folders(const std::string & node_namespace);

  /**
   * @brief Configures the plan solver with runtime parameters.
   *
   * Sets up necessary parameters including command-line arguments for the planner
   * and the output directory for temporary files.
   *
   * @param[in] lc_node Pointer to the lifecycle node.
   * @param[in] plugin_name Name of the plugin to use for parameter namespacing.
   */
  void configure(
    rclcpp_lifecycle::LifecycleNode::SharedPtr lc_node,
    const std::string & plugin_name) override;

  /**
   * @brief Calls the planner to generate a plan for the given domain and problem.
   *
   * This method writes the domain and problem to temporary files, executes the POPF planner,
   * and parses the resulting plan.
   *
   * @param[in] domain PDDL domain description.
   * @param[in] problem PDDL problem description.
   * @param[in] node_namespace Namespace to use for temporary files.
   * @param[in] solver_timeout Maximum time allowed for planning (default: 15 seconds).
   * @return The generated plan if successful, nullopt otherwise.
   */
  std::optional<plansys2_msgs::msg::Plan> getPlan(
    const std::string & domain, const std::string & problem,
    const std::string & node_namespace = "",
    const rclcpp::Duration solver_timeout = 15s);

  /**
   * @brief Checks if a domain is valid by attempting to solve a simple problem.
   *
   * @param[in] domain PDDL domain description to validate.
   * @param[in] node_namespace Namespace to use for temporary files.
   * @return True if the domain is valid, false otherwise.
   */
  bool isDomainValid(
    const std::string & domain,
    const std::string & node_namespace = "");

protected:
  /**
   * @brief Parses the plan output file into a Plan message.
   *
   * Reads the plan file generated by POPF and converts it into the ROS message format.
   * The plan file format is expected to have lines like:
   * "0.0000: (action param1 param2) [duration]"
   *
   * @param[in] plan_path Path to the plan file.
   * @return std::optional<plansys2_msgs::msg::Plan> The parsed plan if successful, nullopt otherwise.
   */
  std::optional<plansys2_msgs::msg::Plan> parse_plan_result(const std::string & plan_path);
};

}  // namespace plansys2

#endif  // PLANSYS2_POPF_PLAN_SOLVER__POPF_PLAN_SOLVER_HPP_
